<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUssvxzy\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUssvxzy/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUssvxzy.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerUssvxzy\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerUssvxzy\EccubeProdProjectContainer([
    'container.build_hash' => 'Ussvxzy',
    'container.build_id' => '5484915b',
    'container.build_time' => 1604395483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUssvxzy');
