<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Plugin\SheebExpandProductColumn\Controller\ConfigController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\Controller.php';
include_once $this->targetDirs[3].'\\src\\Eccube\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Controller\\ConfigController.php';

$a = ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'};

$this->services['Plugin\\SheebExpandProductColumn\\Controller\\ConfigController'] = $instance = new \Plugin\SheebExpandProductColumn\Controller\ConfigController(${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository'] : $this->load('getProductColumnRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository'] : $this->load('getColumnValueRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\CsvRepository']) ? $this->services['Eccube\\Repository\\CsvRepository'] : $this->load('getCsvRepositoryService.php')) && false ?: '_'}, $a);

$instance->setEccubeConfig($a);
$instance->setEntityManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
$instance->setTranslator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
$instance->setSession(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'});
$instance->setFormFactory(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'});
$instance->setEventDispatcher(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});

return $instance;
