<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SheebExpandProductColumn\Repository\ColumnValueRepository' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository.php';

return $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository'] = new \Plugin\SheebExpandProductColumn\Repository\ColumnValueRepository(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\ProductRepository']) ? $this->services['Eccube\\Repository\\ProductRepository'] : $this->getProductRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository'] : $this->load('getProductColumnRepositoryService.php')) && false ?: '_'});
