<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SheebExpandProductColumn\Form\Type\Admin\CustomFileType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Extension\\Core\\Type\\FileType.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Form\\Type\\Admin\\CustomFileType.php';

return $this->services['Plugin\\SheebExpandProductColumn\\Form\\Type\\Admin\\CustomFileType'] = new \Plugin\SheebExpandProductColumn\Form\Type\Admin\CustomFileType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
