<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SheebExpandProductColumn\Form\Type\Admin\ColumnValueType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Form\\Type\\Admin\\ColumnValueType.php';

return $this->services['Plugin\\SheebExpandProductColumn\\Form\\Type\\Admin\\ColumnValueType'] = new \Plugin\SheebExpandProductColumn\Form\Type\Admin\ColumnValueType(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\ProductRepository']) ? $this->services['Eccube\\Repository\\ProductRepository'] : $this->getProductRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository'] : $this->load('getProductColumnRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository'] : $this->load('getColumnValueRepositoryService.php')) && false ?: '_'});
