<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SheebExpandProductColumn\Event' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Event.php';

return $this->services['Plugin\\SheebExpandProductColumn\\Event'] = new \Plugin\SheebExpandProductColumn\Event(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository'] : $this->load('getColumnValueRepositoryService.php')) && false ?: '_'});
