<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SheebExpandProductColumn\Form\Extension\ProductTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractTypeExtension.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Form\\Extension\\ProductTypeExtension.php';

return $this->services['Plugin\\SheebExpandProductColumn\\Form\\Extension\\ProductTypeExtension'] = new \Plugin\SheebExpandProductColumn\Form\Extension\ProductTypeExtension(${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ColumnValueRepository'] : $this->load('getColumnValueRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository'] : $this->load('getProductColumnRepositoryService.php')) && false ?: '_'});
