<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Plugin\SheebExpandProductColumn\Entity\ProductColumn' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Eccube\\Entity\\AbstractEntity.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SheebExpandProductColumn\\Entity\\ProductColumn.php';

return $this->services['autowired.Plugin\\SheebExpandProductColumn\\Entity\\ProductColumn'] = new \Plugin\SheebExpandProductColumn\Entity\ProductColumn();
