<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.a19whmh' shared service.

return $this->services['service_locator.a19whmh'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['productColumnRepository' => function () {
    $f = function (\Plugin\SheebExpandProductColumn\Repository\ProductColumnRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository']) ? $this->services['Plugin\\SheebExpandProductColumn\\Repository\\ProductColumnRepository'] : $this->load('getProductColumnRepositoryService.php')) && false ?: '_'});
}]);
