<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.3r67ipp' shared service.

return $this->services['service_locator.3r67ipp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['ProductColumn' => function () {
    $f = function (\Plugin\SheebExpandProductColumn\Entity\ProductColumn $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Plugin\\SheebExpandProductColumn\\Entity\\ProductColumn']) ? $this->services['autowired.Plugin\\SheebExpandProductColumn\\Entity\\ProductColumn'] : ($this->services['autowired.Plugin\\SheebExpandProductColumn\\Entity\\ProductColumn'] = new \Plugin\SheebExpandProductColumn\Entity\ProductColumn())) && false ?: '_'});
}]);
